name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release

    - name: Publish Artifact
      if: success()
      run: |
        dotnet publish BackendProject.csproj -c Release -o release -nologo
        ls -R release  # Print directory structure for debugging

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: /home/runner/work/BackendProject/BackendProject/release/

